### ISSUE TITLE
Questions About STAR

### ISSUE THREAD

**Issue by ybz79** [cocoxu/simplification#9]
Hi, I have some questions about the STAR.java, I found this script use the f_score of the deletion rather than the precision, which is different from the SARI definition. 
`       

        double recall_del_n = 0.0 ;
        if (delRefTotalNgram > 0) {
                recall_del_n = delCandCorrectNgram / (double) delRefTotalNgram;
        }

        double f1_del_n = meanHarmonic(prec_del_n, recall_del_n);

        sc += weights[n] * f1_del_n;`

Could you tell me the reason?  

Also, I tested STAR on the wiki-small corpus (1 reference ) and I found that using the random sentence as the simplified output can get very high STAR (about 33.7).  Is this a normal phenomenon?

**Comment by cocoxu** [comment]
"For deletion, we only use precision because overdeleting hurts readability much more significantly than not deleting". The python and java implementations of SARI follow this rule. However, STAR (corpus-level SARI) does not. We made this decision for STAR very arbitrarily, since there weren't enough data to verify STAR's correlation with human judgements, given the limited number and varieties of text simplification systems back in 2016. 

As for your second question -- I am not sure how you randomly selected the sentence, and why they would have very hight STAR scores. You may want to look into the separate Delete/Add/Keep scores, as well as SARI scores to figure out the reasons.

**Comment by ybz79** [comment]
Many thanks for your reply!

As for the second question, I found that STAR.java might use the hardcode and fix the number of reference sentences to 8, which may cause this problem when testing on 1-reference corpus.

    HashMap src_sub_cand = substractHashMap(srcNgramCounts[i][n], candNgramCounts[n], 8, 8);
    HashMap src_sub_ref  = substractHashMap(srcNgramCounts[i][n], refNgramCounts[i][n], 8, 1);
    HashMap src_sub_cand_sub_ref = intersectHashMap(src_sub_cand, src_sub_ref, 1, 1)

**Comment by cocoxu** [comment]
Thanks for pointing this out! 

I mostly used SARI for the paper and experiments, though wrote the STAR at some point during the project and released it just in case it might be useful to some people. I added your comments to the README as a temporal "fix" for now.

**Comment by ybz79** [comment]
Many thanks for your reply, I have no more questions.
